---
name: go-module-build 

on:
  workflow_call:
    inputs:
      module_name:
        description: 'Name of the module to build and test'
        required: true
        type: string
      module_path:
        description: 'Path to the module directory'
        required: true
        type: string
      GO_VERSION:
        description: 'Go version to use'
        required: true
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.GO_VERSION }}

    - name: Lint Go Code
      uses: golangci/golangci-lint-action@v6.0.0

    - name: Test ${{ inputs.module_name }}
      run: go test -v ./...
      working-directory: ${{ inputs.module_path }}
    
    - name: Build ${{ inputs.module_name }}
      run: go build -o ${{ inputs.module_name }} ${{ inputs.module_path }}
      working-directory: ${{ inputs.module_path }}
